### ISSUE TITLE
How to populate EasyUI grid from MVC action method

### ISSUE THREAD

**Issue by karlosRivera** [jun0205/EasyUI.Mvc#1]
looking for sample code to populate EasyUI grid from MVC action method.

**Comment by ghost** [comment]
View
@Html.EasyUI().DataGrid().Name("dg").Options(new { singleSelect = true,url="GetProducts", pagination=true,fit=true, striped = true, remoteFilter= true }).Columns(columns =>
    {
        columns.Add(new { field = "name", title = "Ad", width = 100 });
        columns.Add(new { field = "price", title = "Fiyat", width = 100 });
    })
Controller
        public ActionResult GetProducts()
        {
            var list = db.Products.AsQueryable();
            return Json(new {
                total = list.Count(),
                rows = (from p in list
                        orderby p.ProductID select new
                        {
                            name = p.ProductName,
                            price = p.UnitPrice
                        }).Take(10)

```
        },JsonRequestBehavior.AllowGet);
    }
```
